### PR TITLE
docker contribution for linux 

### PR DESCRIPTION
**Pull request by andybe**
This is a step by step docker-compose solution on linux.

- build script creates complete workspace
- seperate build container
- docker-compose.yml
- complete documented
- works in principal from mangos zero - two (small changes are needed)

Only git and docker on host,- no development tools. 

After pull -> links must be corrected in the main README.md

---
This change is [Reviewable](https://reviewable.io/reviews/mangoszero/server/153)

### CODE REVIEW

**Comment by andybe** [comment]
The code factor about apt and apt-get is old. They optimized it for less typing.

**Comment by billy1arm** [comment]
@andybe thanks for your contribution

**Comment by billy1arm** [comment]
> The code factor about apt and apt-get is old. They optimized it for less typing.

I have updated the rules

**Comment by andybe** [comment]
@billy1arm 
can you update the references as I wrote?

README.md: andybe : mangoszero

<h3>Documentation for example docker-compose instance</h3>

- <a href="https://github.com/mangoszero/server/blob/master/contrib/docker/doc/SINGLE.md" >Install mangos as single instance with mangos-zero</a>

- <a href="https://github.com/mangoszero/server/blob/master/contrib/docker/doc/DOCKERCOMPOSE.md" >The "if and way" about the mangos docker-compose.yml</a>

- <a href="https://github.com/mangoszero/server/tree/master/contrib/docker/realm#readme" >Realmd Dockerfile</a>

- <a href="https://github.com/mangoszero/server/tree/master/contrib/docker/world#readme" >Mangos world Dockerfile</a>

**Pull request merged**
