### PR TITLE
Fix "You are in combat" bug.

### PR DESCRIPTION
**Pull request by H0zen**
Ideas taken from TC

### CODE REVIEW

**Comment by ryancheung** [comment]
What if you're in a raid instance, like MC, you'll never get out of combat if you engaged with a Boss unless you died or got out of instance. @H0zen

**Comment by Kittnz** [comment]
Evade?

**Comment by H0zen** [comment]
@ryancheung - thx for feedback, corrected

**Comment by ryancheung** [comment]
@H0zen You're welcome.

**Pull request merged**
