### PR TITLE
Fix Trade Skill Limit

### PR DESCRIPTION
**Pull request by Meltie2013**
**Changes Made:**
- Remove GM Ignore limit configuration as it wasn't working as intended.
- Remove unused configuration from configuration file.

Notice: Accounts with higher permission can still are additional Trade Skills when needed for testing or debugging through the **.learn** command.
Changing Trade Skill limit works as intended from 2 -> 10 as per configuration. Everything else works as normal.

Thanks to @i-am-fyre for some additional testing with this change. Image from another version, but show cases the change being applied.
image

Additional testing will be needed to ensure this is working as intended after limit is reached in Trade Skill learning.
You can pull this PR by using the commands below:
```
git fetch origin pull/192/head:trade-skill-update
git checkout trade-skill-update
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/mangoszero/server/192)

### CODE REVIEW

**Comment by i-am-fyre** [comment]
image
Proof showing 3rd profession is not learnable by trainer.

image2
Additional professions can be learned by using GM .learn command.

**Comment by Meltie2013** [comment]
@billy1arm Any updates for this PR?

**Comment by billy1arm** [comment]
@I'll take a look laterSent from my Galaxy
-------- Original message --------From: Meltie2013 ***@***.***> Date: 27/06/2023  18:30  (GMT+00:00) To: mangoszero/server ***@***.***> Cc: Antz ***@***.***>, Mention ***@***.***> Subject: Re: [mangoszero/server] Fix Trade Skill Limit (PR #192) 
@billy1arm Any updates for this PR?

**Comment by billy1arm** [comment]
@Meltie2013 - Should this be ported to the other cores ?

**Comment by Meltie2013** [comment]
@billy1arm Yeah

**Pull request merged**
