### PR TITLE
Improve Linux Install Script

### PR DESCRIPTION
**Pull request by Pysis868**
Added Fedora 40 support.
Included upgrading ACE requirement to latest stable 7.1.0.
6.3.3 had a stropts compile error.
Added dialog app `fzf`.
Added settings and enabled control from environment.
Propagated database selection control.
Updated and organized, paths and database name(s).
Organized code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mangoszero/server/203)

### CODE REVIEW

**Comment by Pysis868** [comment]
Remaining Codacy code excerpt seems not current, so false positive.
Unknown how to resolve.

https://github.com/mangoszero/server/blob/c905f45f2c69276a472a5b18c26ecf2503baff98/linux/getmangos.sh
```
# We want this to output $ACE_ROOT without expansion.
# This is to be resolved during make compilation, not now.
# shellcheck disable=SC2016
echo 'include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU' >> $ACE_ROOT/include/makeinclude/platform_macros.GNU
echo 'INSTALL_PREFIX=/usr/local' >> $ACE_ROOT/include/makeinclude/platform_macros.GNU
```

**Review by billy1arm — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mangoszero/server/203)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Pysis868)

**Review by billy1arm — CHANGES_REQUESTED** [review]
@Pysis868 can you revert the changes in mangosd.conf.dist.in

The build system populates this and it should not be set to a value

**Comment by Pysis868** [comment]
Confirming `*.in` file removed, and see no others there.
If problem is recreated at all, I suggest gitignore, or may be better, moving actively used file out of source tree, to the build one.

**Comment by Pysis868** [comment]
Relevant Build Messages:
```
CMake Error: File C:/mzero/server_sources/src/mangosd/mangosd.conf.dist.in does not exist.
CMake Error at src/mangosd/CMakeLists.txt:91 (configure_file):
  configure_file Problem configuring file
===================================================
Mangos revision       : 44c6c38c1e80 2024-08-28 19:40:21 +0000 (HEAD branch)
Build type            : Release
Install server(s) to  : C:/mzero/output/server_debugx64
Install configs to    : .
Detailed Information
+-- operating system   : Windows-10.0.17763
+-- cmake version     : 3.29.3
Build main server     : Yes (default)
+-- with Eluna script engine
+-- with SD3 script engine
+-- with PlayerBots
Build login server    : Yes (default)
Support for SOAP      : Yes
Build tools           : Yes (default)
===================================================
-- Configuring incomplete, errors occurred!
Command exited with code 1
```
- https://github.com/mangoszero/server/pull/203#issuecomment-2316125594
- https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/50494321

**Comment by billy1arm** [comment]
Implemented in:
https://github.com/mangoszero/server/commit/5b4c8c0cccff6bf7c20e5be371a6185ac660eb7d

**Pull request closed without merging**
