### PR TITLE
Migrate from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by Meltie2013**
**Changes Proposed:**
- Move from Travis CI to GitHub Actions
- Move from AppVeyor to GitHub Actions (Windows Only)
- Building faster then Travis CI with test builds averaging around 10 minutes, verse 30 minutes or more
- Allows more concurrent builds (22 instead of 4)
- No waiting in Queue line to test compile
- Also it's free to use, no limit caps

**To Do List:**
- [x] Implement Project Compiling
- [x] Add support for Linux Ubuntu 18.04
- [ ] Add support for other Linux Operating Systems
- [x] Add support for Windows
- [ ] Add support for MacOS

**Recommends:**
- [ ] Add support for Codestyling to check for **whitespaces**
- [ ] Add support for Automated PR Labeling

---
This change is [Reviewable](https://reviewable.io/reviews/mangoszero/server/140)

### CODE REVIEW

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.38-jewqhrjm completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/38071828) (commit https://github.com/mangoszero/server/commit/5089f22a08 by @Meltie2013)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.38-opsuexud completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/38074752) (commit https://github.com/mangoszero/server/commit/49b1619065 by @Meltie2013)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.38-suugvstt completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/38074854) (commit https://github.com/mangoszero/server/commit/b80394b915 by @Meltie2013)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.38-nricvbqe completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/38075355) (commit https://github.com/mangoszero/server/commit/e1c0942388 by @Meltie2013)

**Comment by Elmsroth** [comment]
@Meltie2013 @billy1arm Nice proposition !
I vote for it !

**Pull request merged**
