### PR TITLE
Fix teleporting by area triggers.

### PR DESCRIPTION
**Pull request by H0zen**
- Some instances (like Scarlet Monastery) have 2 or more area triggers at the same entrance (e.g. AT 45 and AT 4162 for SM Graveyard). In this case, delaying the far teleport is dangerous.
    - Fixes issue https://www.getmangos.eu/issue.php?issueid=964

### CODE REVIEW

**Comment by H0zen** [comment]
@Olion17 - Disabling delayed teleport in this case guarantees the teleport is finished in a single CMSG_AREATRIGGER processing phase (WorldSession::HandleAreaTriggerOpcode). Also, 2 other facts guarantess the impossibility of entering in ghost form:
1. CMSG_AREATRIGGER is thread unsafe, so it's processed in World::UpdateSessions (single-threaded) which ensures the immutability of Player object
2. The check for IsAlive is done before the call to TeleportTo

**Comment by Olion17** [comment]
OK I agree. This pertains only to the single execution path from `WorldSession::HandleAreaTriggerOpcode`, no other opcode is influenced. While `Player::TeleportTo` is used widely enough, the AreaTrigger parameter is defined by the caller only once. It just means the misplaced functionality, the areatrigger access check must be moved from `TeleportTo` to the handler.

**Comment by H0zen** [comment]
@Olion17 Indeed. And TeleportTo should have a switch for delay/notdelay instead the pointer to areatrigger (a bool isDelayed maybe) for use in non-reentrant cases like this

**Comment by H0zen** [comment]
@billy1arm  This PR is now obsolete, as of PR 80 and should not be merged. I'll close it.

**Pull request closed without merging**
