### PR TITLE
Develop21

### PR DESCRIPTION
**Pull request by Warkdev**
Replacing the use of aptitude by apt-get by default for some Ubuntu versions.

---
This change is [Reviewable](https://reviewable.io/reviews/mangoszero/server/177)

### CODE REVIEW

**Comment by billy1arm** [comment]
@Warkdev - Can you try re pr'ing this, it claims there is a merge failure

**Comment by Warkdev** [comment]
That's a weird issue... I don't understand why the hell git keeps forked repo desync from main repo like that.

**Comment by billy1arm** [comment]
@Warkdev - it does happen from time to time, can you redo it as a new pr ?

**Comment by Warkdev** [comment]
New PR made.

**Pull request closed without merging**
