### PR TITLE
Warden checks refactoring

### PR DESCRIPTION
**Pull request by H0zen**

### CODE REVIEW

**Comment by keyshuwen** [comment]
The patch, ‘mangosd.exe ’ Crash .


2016-03-29 12:20:53 [Warden]: >> Loaded 775 warden checks.
2016-03-29 12:20:53 [Warden]: >> Loaded 0 Warden action overrides. DB table `warden_action` is empty!
2016-03-29 12:21:04 [Warden]: Server side warden for client 55 (build 6141) initializing...
2016-03-29 12:21:04 [Warden]: C->S Key: F44F04716CBE02078008B2B5CC35A624
2016-03-29 12:21:04 [Warden]: S->C Key: 108B867D622FB37EDA83C9D4D4D7DAC6
2016-03-29 12:21:04 [Warden]:   Seed: 4D808D2C77D905C41A6380EC08586AFE
2016-03-29 12:21:04 [Warden]: Loading Module...
2016-03-29 12:21:04 [Warden]: Module Key: AE25BC51063B77BD363C3EFE0FC173F9
2016-03-29 12:21:04 [Warden]: Module ID: 79C0768D657977D697E10BAD956CCED1
2016-03-29 12:21:04 [Warden]: Request module
2016-03-29 12:21:04 [Warden]: Got packet, opcode 01, size 1
2016-03-29 12:21:04 [Warden]: Request hash
2016-03-29 12:21:04 [Warden]: Got packet, opcode 04, size 21
2016-03-29 12:21:04 [Warden]: Request hash reply: succeed
2016-03-29 12:21:04 [Warden]: Initialize module
2016-03-29 12:21:14 [Warden]: Request data
2016-03-29 12:31:12 [Warden]: >> Loaded 775 warden checks.
2016-03-29 12:31:12 [Warden]: >> Loaded 0 Warden action overrides. DB table `warden_action` is empty!
2016-03-29 12:32:29 [Warden]: Server side warden for client 55 (build 6141) initializing...
2016-03-29 12:32:29 [Warden]: C->S Key: 7C076F9159584AB3142F4F94FEC49ADB
2016-03-29 12:32:29 [Warden]: S->C Key: D41019CB5AD30972075CB8FB91A774B2
2016-03-29 12:32:29 [Warden]:   Seed: 4D808D2C77D905C41A6380EC08586AFE
2016-03-29 12:32:29 [Warden]: Loading Module...
2016-03-29 12:32:29 [Warden]: Module Key: AE25BC51063B77BD363C3EFE0FC173F9
2016-03-29 12:32:29 [Warden]: Module ID: 79C0768D657977D697E10BAD956CCED1
2016-03-29 12:32:29 [Warden]: Request module
2016-03-29 12:32:29 [Warden]: Got packet, opcode 01, size 1
2016-03-29 12:32:29 [Warden]: Request hash
2016-03-29 12:32:29 [Warden]: Got packet, opcode 04, size 21
2016-03-29 12:32:29 [Warden]: Request hash reply: succeed
2016-03-29 12:32:29 [Warden]: Initialize module
2016-03-29 12:32:39 [Warden]: Request data.

Crash..

Sorry, my English is not very good.

**Comment by H0zen** [comment]
@keyshuwen - thanks for the feedback, we are working to fix this issue as soon as possible

**Comment by billy1arm** [comment]
@keyshuwen - this should now to fixed in https://github.com/mangoszero/server/commit/bd0e8c774f935dc735667264694d95f1bded5389

**Comment by keyshuwen** [comment]
Very good.

**Pull request merged**
