### PR TITLE
Dire Maul fixes and gameObject AI implementation

### PR DESCRIPTION
**Pull request by Elmsroth**
WArning SD3 module and Eluna module updated .. nedd attention during merge :)

### CODE REVIEW

**Comment by MadMaxMangos** [comment]
:x: [Build Mangos ZERO Server 21.17.19-lyyhmtwf failed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/33191089) (commit https://github.com/mangoszero/server/commit/7a39b3886d by @Elmsroth)

**Comment by MadMaxMangos** [comment]
:x: [Build Mangos ZERO Server 21.17.19-ptlnikuj failed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/33191094) (commit https://github.com/mangoszero/server/commit/63fa2ddb2f by @Elmsroth)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 21.17.19-wiphvyci completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/33191277) (commit https://github.com/mangoszero/server/commit/c3436f2875 by @Elmsroth)

**Comment by Elmsroth** [comment]
The build seems to pass now :) Only linux build was failing du to a missing 
`#include <memory>` 
in order to use `std::unique_ptr` template.

**Comment by Elmsroth** [comment]
Well @AntzMangos / @billy1arm 
Do you want me to squash these commits ? Because With submodule impact i do not know if it will work well.

**Comment by billy1arm** [comment]
@Elmsroth - It's ok, i can merge them

**Pull request merged**
