### PR TITLE
Refactor Account & Password Length

### PR DESCRIPTION
**Pull request by Meltie2013**
Added password length check and refactored rest of the code.

---
This change is [Reviewable](https://reviewable.io/reviews/mangoszero/server/129)

### CODE REVIEW

**Comment by Elmsroth** [comment]
Thanks @Meltie2013 !

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.17-ovgniaqu completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37535883) (commit https://github.com/mangoszero/server/commit/197fb74fd3 by @Meltie2013)

**Review by billy1arm — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mangoszero/server/129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Meltie2013)

**Comment by billy1arm** [comment]
@Meltie2013 - Any idea if this limit applies to the other cores ?

**Comment by Meltie2013** [comment]
@billy1arm Yes, mostly all of them since username and password lengths are hardcoded in the clients.

**Pull request merged**
