### PR TITLE
[Core] Account Manager Rework

### PR DESCRIPTION
**Pull request by Meltie2013**
**Changes Made**
* Update AccountMgr class to static class
* Move AccountOpResult enum to enum class
* Replace old normalize string method to a newer version
* Update misc code around the class itself
* Replace ACE Singleton with C++ version

**Notice:** Eluna build fails till it is updated to support newer changes.

---
This change is [Reviewable](https://reviewable.io/reviews/mangoszero/server/157)

### CODE REVIEW

**Comment by billy1arm** [comment]
@Meltie2013 have you raised a pr against the eluna repo ?

**Comment by Meltie2013** [comment]
> @Meltie2013 have you raised a pr against the eluna repo ?

Not yet, but will later on.

**Comment by Meltie2013** [comment]
Commit Reference: https://github.com/Meltie2013/Eluna/commit/337276b17521c1a258dd3f8cab0aa58a56fb74ec

**Comment by Meltie2013** [comment]
@billy1arm This is ready to be merged. This is building with all the changes made on this and Eluna.

**Comment by billy1arm** [comment]
> @billy1arm This is ready to be merged. This is building with all the changes made on this and Eluna.

@Meltie2013  Just waiting for the Eluna PR to be approved and i'll merge this

**Comment by billy1arm** [comment]
@Meltie2013 In future, Please try and keep pr's to a single functionality change, this helps should a change for one part needs to be reverted. In this instance, had the soap changes been separate, they could be merged immediately.

**Comment by Meltie2013** [comment]
@billy1arm It's a single functionality change, that last commit has to do with a forgotten change for Soap to support the AccountMgr change. During the change, forgot I didn't have Soap enabled else the build would fail.

**Comment by Meltie2013** [comment]
Abandoning this PR do to inactivity on Eluna side.

**Pull request closed without merging**
