### PR TITLE
Rewrote extractor for Unix/Linux so it works again

### PR DESCRIPTION
**Pull request by The-Great-Sephiroth**
This is a temporary fix created on-the-fly to make the resource extraction work correctly under *nix systems again. I will be working on an updated version which takes advantage of multiple cores/CPUs again in a bit. It should be done by tomorrow, and it should be one single script. This works, but only uses one core. Again, this is a quick fix.

### CODE REVIEW

**Comment by billy1arm** [comment]
This seems to be based on an old version of the extraction tools as the two vmap tools were merged into a single tool.

The tools source are now their own submodule located at: https://github.com/mangos/Extractor_projects

**Comment by The-Great-Sephiroth** [comment]
I cloned the repo using "--recursive" Monday. Are only the Windows tools combined? I did notice that in the notes but in Linux it STILL builds separate tools.

**Comment by billy1arm** [comment]
@The-Great-Sephiroth - Did you clean the CMAKE_INSTALL_PREFIX folder ?

In the source code, the whole vmap-assembler directory has been removed, including its CMakeLists.txt, so it's impossible to build it together with the vmap-extractor

**Comment by The-Great-Sephiroth** [comment]
It built two separate utilities for me on Monday. I will backup my personal changes, delete my fork, refork, and try again tonight.

**Comment by billy1arm** [comment]
@The-Great-Sephiroth - Any News ?

**Comment by billy1arm** [comment]
@The-Great-Sephiroth - Please reissue if you think it's still required !

**Pull request closed without merging**
