### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by Elmsroth**

### CODE REVIEW

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 21.17.60-kyimcsgs completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/36076380) (commit https://github.com/mangoszero/server/commit/672d61393e by @Elmsroth)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 21.17.60-kqhbkhjf completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/36076545) (commit https://github.com/mangoszero/server/commit/d12a0f7c72 by @Elmsroth)

**Comment by MadMaxMangos** [comment]
:x: [Build Mangos ZERO Server 21.17.60-ucmwcjyy failed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/36077258) (commit https://github.com/mangoszero/server/commit/21465a50a9 by @Elmsroth)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 21.17.60-pxvtdfpl completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/36099063) (commit https://github.com/mangoszero/server/commit/9a52b44055 by @Elmsroth)

**Comment by Elmsroth** [comment]
It can be merged

**Pull request merged**
