### PR TITLE
Internal Timer Rewrite & Introduce GameTime

### PR DESCRIPTION
**Pull request by Meltie2013**
Ensure that actions are compared to fixed point in time. (e.g. Make sure timers are stable and trigger when they are scheduled too and not at random points in time before/after scheduled time happens)

- [x] Implement Duration Helper
- [x] Revamp Internal Timer
- [x] Replace WorldTimer with GameTime
- [x] Submodule Checks
- [ ] Rewrite Cleanup

**Notice:** Eluna will need to be updated to support the changes in this PR, else the build will fail.

---
This change is [Reviewable](https://reviewable.io/reviews/mangoszero/server/132)

### CODE REVIEW

**Comment by MadMaxMangos** [comment]
:x: [Build Mangos ZERO Server 22.01.18-uytenehc failed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37564614) (commit https://github.com/mangoszero/server/commit/0dfeb80f54 by @Meltie2013)

**Comment by Elmsroth** [comment]
@Meltie2013 it seems build is failing :)

**Comment by Meltie2013** [comment]
@Elmsroth Its because of Eluna not being compatible with the change yet. Working on a work around till that change is made.

**Comment by MadMaxMangos** [comment]
:x: [Build Mangos ZERO Server 22.01.18-bhohytbo failed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37566872) (commit https://github.com/mangoszero/server/commit/203f4556b8 by @Meltie2013)

**Comment by MadMaxMangos** [comment]
:x: [Build Mangos ZERO Server 22.01.18-bqqihwuo failed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37569397) (commit https://github.com/mangoszero/server/commit/89b8787148 by @Meltie2013)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.18-fkqisqmf completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37573291) (commit https://github.com/mangoszero/server/commit/8a10c23fb7 by @Meltie2013)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.19-qrkkxdgm completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37576340) (commit https://github.com/mangoszero/server/commit/1e97f81044 by @Meltie2013)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.19-lruwgrly completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37578386) (commit https://github.com/mangoszero/server/commit/fe3605b821 by @Meltie2013)

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.23-trsthdop completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37618918) (commit https://github.com/mangoszero/server/commit/51f19cdc8d by @Meltie2013)

**Comment by Meltie2013** [comment]
@billy1arm The Codacy action will be fixed on another rewrite planned for the world daemon in upcoming rewrite/refactor.

**Comment by MadMaxMangos** [comment]
:white_check_mark: [Build Mangos ZERO Server 22.01.25-qfssirsf completed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/37663073) (commit https://github.com/mangoszero/server/commit/fb661501b6 by @Meltie2013)

**Comment by Foereaper** [comment]
Eluna should now be updated with the required changes, remember to update the Eluna submodule after accepting this PR

**Comment by MadMaxMangos** [comment]
:x: [Build Mangos ZERO Server 22.01.34-cygjmooh failed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/38029655) (commit https://github.com/mangoszero/server/commit/8ad624c58d by @Foereaper)

**Comment by MadMaxMangos** [comment]
:x: [Build Mangos ZERO Server 22.01.34-belvxbre failed](https://ci.appveyor.com/project/MaNGOS/server-9fytl/builds/38030001) (commit https://github.com/mangoszero/server/commit/ad14247cf9 by @Foereaper)

**Pull request merged**
