### PR TITLE
Make Mangos Zero compatible with newer MySQL

### PR DESCRIPTION
**Pull request by leprasmurf**
When running Mangos Zero with SQL > 5.7 different bugs start to crop up.  Specifically, guild inserts were failing.  This PR adds a backtick delimiter to the columns and tables.

I'm running these changes on my own server and watching the console for errors.  As I find more I'll update the PR.

### CODE REVIEW

**Comment by billy1arm** [comment]
@leprasmurf - Is this ready to be merged ?

**Comment by leprasmurf** [comment]
@billy1arm: sorry it's taking so long, there are a lot of queries to escape.

**Comment by leprasmurf** [comment]
Ok @billy1arm I think I might have gotten what I can.  This compiles for me, though I noticed Travis CI is complaining:

```
/System/Library/Frameworks/Security.framework/Headers/cssmconfig.h:51:18: error: typedef redefinition with different types ('uint64_t' (aka 'unsigned long long') vs 'ACE_UINT64' (aka 'unsigned long'))
typedef uint64_t uint64;
```

Guilds have been working for me this week after these changes.

**Comment by billy1arm** [comment]
That ACE error is an outstanding error on the MAC OS build, which i'm unable to resolve as a don't have access to a MAC.

I'll merge this later today, thanks for your contribution.

**Comment by leprasmurf** [comment]
@billy1arm: I've been running this branch for a few days now, it's been stable for me.  I did hit a sql error I couldn't track down.  I think the sql may be the return of some other function, mostly because grep was failing me.

My logs have been clear of sql errors since around my last push:

```
root@wowclassic01:/var/log/mangos# grep -iR -e 'error.*sql' -e 'sql.*error' *.log | awk -F'[: ]*' '{print $2}' | sort -u
2020-04-07
2020-04-08
2020-04-09
2020-04-10
2020-04-11
root@wowclassic01:/var/log/mangos# date
Wed Apr 15 21:33:52 UTC 2020
```

**Pull request merged**
